include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for victron-ve-direct
LUCI_DEPENDS:=+luci-base +victron-ve-direct +rpcd

PKG_MAINTAINER:=Jaco Hanekom <jhanekom@gmail.com>
PKG_LICENSE:=custom

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
